name = "Cccc's-Simple-Modpack-1.16.5"
author = "Cccc_"
version = "v1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47d4c0903fa08b2e46f95c793f9d70056c0cd1fec67fdb74a8a04b93b31159a9"

[versions]
fabric = "0.14.8"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16", "1.16.1", "1.16.2", "1.16.3", "1.16.4", "1.16.5"]
