name = "Cccc's-Simple-Modpack"
author = "Cccc_"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "deae0e290918b88913465aa7f8adcc9ed05d5af58f39a6eee2bfec189c7e7d8b"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
