name = "Cccc's-Simple-Modpack"
author = "Cccc_"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3de44794226142163ceabb410ddbb179ed8ca0113cbcde5d3230ea5b0113688"

[versions]
fabric = "0.14.8"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16", "1.16.1", "1.16.2", "1.16.3", "1.16.4", "1.16.5"]
