name = "Cccc's-Simple-Modpack-1.18.2"
author = "Cccc_"
version = "v1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57e1533b066217e98f7b87133179d0fe76fff6e7df2d6518aef0895e10d6b48b"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
