name = "Cccc's-Simple-Modpack"
author = "Cccc_"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86fc64c5328b7684cbcab576f36f2282e9387a20b7239bfda5520243fb7dff12"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
