name = "Cccc's-Simple-Modpack-1.19"
author = "Cccc_"
version = "v1.1.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41db86fc16e780da30cdce1f59ba6402498ceb4831986aec8190e6d8816a49bd"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
