name = "Cccc's-Simple-Modpack-1.19"
author = "Cccc_"
version = "v1.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2a91e14ae3eb27786a6bdeb87e3a6eb6f4ec953f8fe1db31b7734132ec7fa4b"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
