name = "Cccc's-Simple-Modpack-1.18.2"
author = "Cccc_"
version = "v1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa63abd0d6eea718090a011d66c5971e9043837bff82fd5c1d5f2dbb0bcccd6c"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
