name = "Cccc's-Simple-Modpack-1.18.2"
author = "Cccc_"
version = "v1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "494fa244dda39361b7aa065ddf0be39fa5002175ff893e2378ac5e9569cb21c5"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
