name = "Cccc's-Simple-Modpack"
author = "Cccc_"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e00431d6e5c419f510207e189814ed3360a10071587a4efcac2193e45823eb24"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
