name = "Cccc's-Simple-Modpack-1.18.2"
author = "Cccc_"
version = "v1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d46d1cb54c9f31a337d465e58578ef576ace5802b639e69dfea22c8024d0feb"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
