name = "Cccc's-Simple-Modpack"
author = "Cccc_"
version = "1.19-v1.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "01839fe489463fc5a12509cb3e39fadda2e831c48f15a7fb928e6f5bd5d918ae"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
