name = "Cccc's Simple Modpack"
author = "Cccc_"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2d84a08faa066eed5c47579b7a29de4373e8f27783ec1ba3094d8ef85263928"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
