name = "Cccc's-Simple-Modpack-1.19"
author = "Cccc_"
version = "v1.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "01ee39b7656611ee32bc5d8d18754ff0346a4f3be5418cdf48eb84924cd54cf5"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
