name = "Cccc's-Simple-Modpack"
author = "Cccc_"
version = "1.19-v1.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54b7a6a572022798b39f4c0193759e35cea6e305b4cb964458add261f21ba5e9"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
